on:
  push:
    branches:
      - master
jobs:
  label_conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: mschilde/auto-label-merge-conflicts@v2.0
        with:
          CONFLICT_LABEL_NAME: "Merge Conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
