# .github/workflows/main.yaml
name: Main

on: [push, pull_request]

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
    - uses: harmon758/postgresql-action@v1
    - uses: actions/checkout@master

    - name: Set up Ruby 2.5.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.5

    # required to compile pg ruby gem
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev

    - name: Build and create DB
      env:
        PG_HOST: postgres
        PG_DATABASE: postgres
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports['5432'] }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup

    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        bundle exec rspec
