# .github/workflows/main.yaml
name: Main

on: [push, pull_request]

jobs:
  vm-job:
    runs-on: ubuntu-latest


    steps:
    - uses: harmon758/postgresql-action@v1
    - uses: actions/checkout@master

    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev

    - name: Set up Ruby 2.5.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.5

    - name:  bundle install & run rubocop
      run: |
        gem install bundler
        gem install rubocop
        bundle install --jobs 4 --retry 3
        git ls-files -m | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs rubocop
