name: Do a thing on release
on:
  release:
    types: # This configuration does not affect the page_build event above
      - published
jobs:
  on_release:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: |
          echo this works

