name: Rebase PR Branch with Master
on: [pull_request]
jobs:
  rebase_pr_branch_with_master:
    if: "!startsWith(github.ref, 'refs/tags/') && \
         github.ref != 'refs/heads/master' && \
         github.ref != 'refs/heads/production' && \
         !startsWith(github.ref, 'refs/heads/release') && \
         !startsWith(github.ref, 'refs/heads/hotfix')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: git fetch --prune --unshallow
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
